### ISSUE TITLE
Need to fix getPlayerGreencoinsLogin() exported function (gc resource)

### ISSUE THREAD

**Issue by AleksCore** [JarnoVgr/Mr.Green-MTA-Resources#146]
@EsDeKa said it's probably because of new greencoins API.

**Comment by JarnoVgr** [comment]
What is exactly the problem?

**Comment by EsDeKa** [comment]
Well it's actually because of the new autologin
Like I said to you earlier, you can only get the current forum name through the api with the user's password

Autologin currently skips the api so it doesn't know the username

Solutions:

1. save the username on manual login in autologin table
2. get it from members table in db (ywa does not like that)
3. new api part so we can get it from there

**Comment by JarnoVgr** [comment]
Would an API login by forum member id be ok?

**Comment by EsDeKa** [comment]
That would be great
