### ISSUE TITLE
/duel problem

### ISSUE THREAD

**Issue by Flipper123** [JarnoVgr/Mr.Green-MTA-Resources#158]
every time /duel starts i get really low fps, and big lagg, some players said they have same problem

**Comment by Flipper123** [comment]
![image](https://cloud.githubusercontent.com/assets/16647544/13431555/32c5191c-dfca-11e5-8ba0-1f2d5dc218ec.png)

duel ramp is in every map, not only in dd, and when u go near it in map, like in nts, u get low fps

**Comment by AleksCore** [comment]
Guess there is over 9000 objects loaded. :) Just a guess

**Comment by Flipper123** [comment]
idk :D

**Comment by EsDeKa** [comment]
I restarted the resource, does the problem still exist?

**Comment by Flipper123** [comment]
no, no low fps or lagg anymore

**Comment by AleksCore** [comment]
Guess it was because they use /duel when duel already launched. 

So it creates new maproot element and it never destroy previous elements/objects. It destroy only root elements attached to "maproot" variable which redefines every time when they type /duel.

function startDuel(p, c, a)
...
maproot = loadMapData ( node, resourceRoot )
...
end
addCommandHandler('duel', startDuel, true)
