### ISSUE TITLE
MTA recent subform topics not updating ingame

### ISSUE THREAD

**Issue by f1madkiller** [JarnoVgr/Mr.Green-MTA-Resources#160]
the recent MTA sub forum topic ingame is not updating for some reason, since forum update it seems broken

**Comment by Flipper123** [comment]
ye i saw that, only says MTA resent subforum topics, nothing else

**Comment by f1madkiller** [comment]
I think since the forum updates something is not synicing prob a Ywa fix

**Comment by EsDeKa** [comment]
Parser needs to be updated, probably can use this rss feed now https://mrgreengaming.com/forums/forum/31-multi-theft-auto.xml

**Comment by AleksCore** [comment]
kewl, could make it later

**Comment by AleksCore** [comment]
https://mrgreengaming.com/forums/forum/31-multi-theft-auto.xml
This XML file does not appear to have any style information associated with it. The document tree is shown below.

Ehh shitty. Can't download(fetch) this XML as I did with https://github.com/JarnoVgr/Mr.Green-MTA-Resources/commits/master.atom

It isn't real XML

**Comment by AleksCore** [comment]
@JarnoVgr is it hard to make Atom feed for our forums?

**Comment by JarnoVgr** [comment]
Why can't MTA read the file? It's XML-like

**Comment by AleksCore** [comment]
It can be read by MTA, but sadly can't be read using MTA API XML functions. 

Can be read using default Lua string functions (string.find, etc). Shouldn't be very hard probably, don't know.

And as I said there is no nicknames in this rss(?)-feed. With nicknames looks better though.

Maybe better to use https://mrgreengaming.com/forums/forum/31-multi-theft-auto/ instead of https://mrgreengaming.com/forums/forum/31-multi-theft-auto.xml

**Comment by JarnoVgr** [comment]
Scraping/parsing the full HTML page is a bad idea. I'll look into the users missing from the XML.

**Comment by EsDeKa** [comment]
3a24aad30a863077aa4d89dafba1f95211f0bd36

Seems to work, not sure what you did Aleks
If Ywa now manages to add the users to the rss feed, it would be ideal

**Comment by JarnoVgr** [comment]
Opened #166 , closing this one
